### ISSUE TITLE
add filter options into the url

### ISSUE THREAD

**Issue by ccmmaa** [ccmmaa/idb#103]

**Comment by ChiaHuaLu** [comment]
Done. See #101

**Comment by ChiaHuaLu** [comment]
Examples: 
Sort by name in decending order, with filters 1973 and 1976:
http://localhost/albums?sort=name&dir=dec&filters=[1973,1976]

Sort by ascending ID, with Atlanta order, page 6
http://localhost/songs?filters=[4]&p=6
