### ISSUE TITLE
(Estimate 8 hours) Filter songs and albums by genre

### ISSUE THREAD

**Issue by cindyqtruong** [ccmmaa/idb#115]
As a user browsing albums or songs, I would like to be able to filter albums or songs by genre, similar to artists. 

Assumptions:
- all albums have genres
- all songs have genres
- design can support multiple filters of different types

Estimated time: 12 hours

**Comment by SabrinaHerrero** [comment]
shouldn't take long. Just copy the code from the artist filter

**Comment by ChiaHuaLu** [comment]
That is incorrect. After copying the artist filter, also have to adapt the URL/State/request mechanism. Estimate maybe 4 hours each? so 8 hours

**Comment by ChiaHuaLu** [comment]
Completed
