### ISSUE TITLE
Feedback when no search results are found

### ISSUE THREAD

**Issue by cindyqtruong** [ccmmaa/idb#116]
As a user making searches, I'd like searches that return no results to give feedback indicating that this is the case (e.g., a line that says, "No results found").

Assumptions:
- design allows for detecting when 0 results are found for a search

Estimated time: 2 hours

**Comment by Laurencez** [comment]
Looking into this. Shouldn't take too long. Thanks for the suggestion!

**Comment by Laurencez** [comment]
Added if clause that checked if the data returned from search call was empty. If so, returns feedback on page stating that no results were found. Total time [.25 hrs]
