### ISSUE TITLE
Names on cards as links

### ISSUE THREAD

**Issue by cindyqtruong** [ccmmaa/idb#117]
As a user browsing all the various instances, I would like to be able to click on the names of songs, albums, genres, and cities to go to their pages, as opposed to only being able to click on the pictures or View button .

Assumptions:
- hyperlinking the titles doesn't magically break your cards somehow

Estimated time: 0.5 hour

**Comment by Laurencez** [comment]
Seems like a good idea. I'll add references linking the names to the instance page

**Comment by Laurencez** [comment]
Added hyperlinks to any text on cards that wasn't linking to the instance page. Total time [0.25 hrs]
