### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by cindyqtruong** [ccmmaa/idb#118]
As a user who stumbled across an invalid page, I want to be instantly aware of that through some kind of 404 page.

Assumptions:
- can create a 404 component/template
- can route invalid pages to that component/template

Estimated time: 4 hours

**Comment by ChiaHuaLu** [comment]
If requesting an invalid instance page, a 404 error shows.

**Comment by ChiaHuaLu** [comment]
Made a Error.js that handles 404, 400, and other errors
