### ISSUE TITLE
(Est 3 hrs) Artist bio format [Act 1 hr]

### ISSUE THREAD

**Issue by cindyqtruong** [ccmmaa/idb#119]
As a user reading artist bios, I would like to click on the link provided to read the source. (The link tag currently shows as plaintext.)

Relatedly, nicer formatting would be preferable.

Assumptions:
- can assume bio is always safe to decode to HTML
- alternatively, that the bio always has the "Read more on Last.fm" link with a predictable URL

Estimated time: 3 hours

**Comment by Laurencez** [comment]
Parsed through the bio to find the link to the last.fm site for the artist and set that as a hyperlink on our artist instance. Will need to check what happens in the case where a bio doesn't exist for an artist.

**Comment by Laurencez** [comment]
Need to fix issue where the "Read more on last.fm" appears even when the artist has no bio. The hyperlink links to current artist instance page

**Comment by Laurencez** [comment]
Fixed. Total time was about [1 hr]
