### ISSUE TITLE
Mobile text too small 

### ISSUE THREAD

**Issue by cindyqtruong** [ccmmaa/idb#121]
The text scales down drastically on mobile or when resizing the page. As a mobile user, it'd be nice to have the font be a more legible size regardless of device/window size. 

Assumptions:
- can change how the text scales based on device/window size

Estimated time: 4 hours

**Comment by ChiaHuaLu** [comment]
Unable to make website suitable for both Desktop and Mobile. Opted to just make website consistent across different screen sizes instead.
