### ISSUE TITLE
Navbar on mobile not functional

### ISSUE THREAD

**Issue by cindyqtruong** [ccmmaa/idb#122]
The dropdown menu button is not functional on mobile or when resizing the page. As a mobile user, it'd be nice to have access to the navbar. 

Assumptions:
- can adjust navbar depending on device/window size

Estimated time: 4 hours

**Comment by ChiaHuaLu** [comment]
Fixed CSS style that allows normal navbarto show up on mobile website. 
Took around 30 minutes
