### ISSUE TITLE
Unusual back behavior on song pages

### ISSUE THREAD

**Issue by cindyqtruong** [ccmmaa/idb#123]
When going back from a song instance page, the website stalls and requires clicking back again. The Spotify widget for playing the song is perpetually loading when this happens. This is possibly due to it being an iframe.

Assumptions: 
- can work out how to adjust back behavior with iframes

Estimated time: 8 hours

**Comment by SabrinaHerrero** [comment]
I'm not sure what this is referring to?

**Comment by ChiaHuaLu** [comment]
When I visit the Song Instance page, when I click the back button, it takes me to whichever page of the All Page that I came from. Seems to work properly.

**Comment by SabrinaHerrero** [comment]
Unable to recreate issue
