### ISSUE TITLE
Make filter URLs more human readable 

### ISSUE THREAD

**Issue by SabrinaHerrero** [ccmmaa/idb#125]
Example: http://musepy.me/songs?filters=[11] is the filter for Jacksonville but thats not obvious from the URL

**Comment by ChiaHuaLu** [comment]
Completed for Songs Page. Took maybe 1 hr

**Comment by ChiaHuaLu** [comment]
"filters":[{
  "or":[{ 
    "name":"city",
    "op":"has",
    "val":{
      "name":"name",
      "op":"eq",
      "val":"Atlanta"
    }
  }]
}]
