### ISSUE TITLE
server does not let other computers access website

### ISSUE THREAD

**Issue by ccmmaa** [ccmmaa/idb#28]

**Comment by ChiaHuaLu** [comment]
Flask "Server" does serve it to the machine itself at 127.0.0.1, but that's it. Outside machines cannot access it. Maybe put the flask server into another serving program?

**Comment by ccmmaa** [comment]
https://www.datasciencebytes.com/bytes/2015/02/24/running-a-flask-app-on-aws-ec2/

**Comment by ChiaHuaLu** [comment]
it works if instead of
export FLASK_APP=idb.py
python3 -m flask run

DO THIS INSTEAD:
export FLASK_APP=idb.py
flask run --host=0.0.0.0
