### ISSUE TITLE
[est 3 hrs] Make the Home page with react (Actual 1.5 hour)

### ISSUE THREAD

**Issue by ChiaHuaLu** [ccmmaa/idb#50]

**Comment by ChiaHuaLu** [comment]
Home page done. No api needed

**Comment by Laurencez** [comment]
Had to fix carousel because it wasn't working dynamically. Eventually decided to import modules from react-strap in order to fix the issue.

**Comment by Laurencez** [comment]
Changed the actual time to 3.5 hrs
