### ISSUE TITLE
[est 6 hrs] Make model and controllers python files

### ISSUE THREAD

**Issue by ccmmaa** [ccmmaa/idb#59]

**Comment by SabrinaHerrero** [comment]
models so far have taken about 3.75 hours. Still trying to figure out how best to represent many to many mappings

**Comment by SabrinaHerrero** [comment]
Worked about 6 hours yesterday and have connection to the database. Working on getting the API together

**Comment by SabrinaHerrero** [comment]
Working right now on getting the mappings connected in the database and in flask

**Comment by SabrinaHerrero** [comment]
used flask_restless everything worked a lot better
