### ISSUE TITLE
API Not enough information

### ISSUE THREAD

**Issue by ChiaHuaLu** [ccmmaa/idb#62]
For Songs, spotify url is required.
No itunes link provided
Which city is this song's City?

Cities model don't have pictures

Artist Instances, missing Slide picture at the top, 

Cities: no way to get city picture

**Comment by ChiaHuaLu** [comment]
We don't need gender in Artists

**Comment by ccmmaa** [comment]
we should be writing the API in Postman

**Comment by ccmmaa** [comment]
finished writing the API
