### ISSUE TITLE
[est 2 hrs] Create API subdomain (Actual 5 Hrs)

### ISSUE THREAD

**Issue by SabrinaHerrero** [ccmmaa/idb#66]

**Comment by ChiaHuaLu** [comment]
Used Route53 to register the subdomain, and pointed it to a new instance of EC2 that is separate from the normal instance. The api server will run flask on port 80, and website server will run react on port 80.

**Comment by SabrinaHerrero** [comment]
Had to set url_prefix to None for the API as well. 
https://flask-restless.readthedocs.io/en/latest/api.html
