### ISSUE TITLE
(Est 5 hrs) Add filtering to the model pages [Act ]

### ISSUE THREAD

**Issue by ccmmaa** [ccmmaa/idb#72]

**Comment by ccmmaa** [comment]
Filter Albums by:
Artist - the artist of the album - Type: Artist Object
Genre - the genre of the album - Type: String
Producer - producer of the album - Type: String
Release Date - date the album was released - Type: Int

Filter Artists by:
Concerts - list of the concerts that the artist is performing at - Type: Array with Concert Objects
Genre - the genre that the artist is associated with - Type: Strings
(Idea) Filter artists based on when they are active using the release date of the album

Filter Cities by:
Concerts - list of the concerts happening in that city - Type: Array with Concert Objects
State - the state that the city is in - Type: String
Songs - list of the songs in the playlist - Type: Array with Songs Objects ???

Filter Songs by:
Album - the album that the song is on - Type: Album Object
Artist - the artist that made the song - Type: Artist Object
City - a city that has a playlist that has the song - Type: City Object

**Comment by ChiaHuaLu** [comment]
Probably did like 4 hours last week. 
2 Hours today.

**Comment by faizm123** [comment]
Note: Had to use "or" in the filter because without it, the API would filter based on first filter then second filter so it wasn't possible to filter with two different genres, years, etc.

**Comment by ChiaHuaLu** [comment]
did 2 hours to connect the back end of filtering to front end

**Comment by faizm123** [comment]
http://api.musepy.me/song?q={%22filters%22:[{%22name%22:%22city_id%22,%22op%22:%22eq%22,%22val%22:%221%22}]}

**Comment by faizm123** [comment]
Same as above but readable: http://api.musepy.me/song?q={"filters":[{"name":"city_id","op":"eq","val":"1"}]}

**Comment by faizm123** [comment]
http://api.musepy.me/artist?q={"filters":[{"or":[{"name":"genre","op":"eq","val":"alternative metal"},{"name":"genre","op":"eq","val":"hip hop"}]}]}

**Comment by faizm123** [comment]
Same as above but full url: http://api.musepy.me/artist?q={"filters":[{"or":[{"name":"genre","op":"eq","val":"alternative%20metal"},{"name":"genre","op":"eq","val":"hip%20hop"}]}]}

**Comment by faizm123** [comment]
http://api.musepy.me/album?q={"filters":[{"or":[{"name":"year","op":"eq","val":"2008"},{"name":"year","op":"eq","val":"2000"},{"name":"year","op":"eq","val":"2016"}]}]}
