### ISSUE TITLE
(Est 5 hrs) Implement sorting for model pages [Act 4]

### ISSUE THREAD

**Issue by ccmmaa** [ccmmaa/idb#74]

**Comment by ccmmaa** [comment]
Sort Albums by:
Artist - the artist of the album - Type: Artist Object
Genre - the genre of the album - Type: String
Name - the name of the album - Type: String (A-Z and Z-A)
Producer - producer of the album - Type: String

Sort Artists by:
Songs - list of the songs that the artist's songs - Type: Array with Song Objects (# of songs)
Name - the name of the artist - Type: String
Concerts - list of the concerts that the artist is performing at - Type: Array with Concert Objects (# of concerts, concert date)
Genre - the genre that the artist is associated with - Type: Strings

Sort Cities by:
Concerts - list of the concerts happening in that city - Type: Array with Concert Objects (# of concerts, concert date)
State - the state that the city is in - Type: String
Songs - list of the songs in the playlist - Type: Array with Songs Objects(# of songs)
Name - name of the city - Type: String

Sort Song by:
Album - the album that the song is on - Type: Album Object
Artist - the artist that made the song - Type: Artist Object
Name - name of the song - Type: String
City - a city that has a playlist that has the song - Type: City Object

**Comment by SabrinaHerrero** [comment]
Also sort albums and songs by release year

**Comment by SabrinaHerrero** [comment]
sort by genre for songs as well?

**Comment by SabrinaHerrero** [comment]
not sure how to sort by number of songs or by number of concerts

**Comment by SabrinaHerrero** [comment]
Albums:

http://localhost:/album?q={"order_by":[{"field":"name","direction":"desc"}]}
http://localhost:/album?q={"order_by":[{"field":"artist__genre","direction":"desc"}]}
http://localhost:/album?q={"order_by":[{"field":"artist__name","direction":"desc"}]}
http://localhost:/album?q={"order_by":[{"field":"producer","direction":"desc"}]}
http://localhost:/album?q={"order_by":[{"field":"year","direction":"desc"}]}

Songs: 

http://localhost:/song?q={"order_by":[{"field":"album__name","direction":"desc"}]}
http://localhost:/song?q={"order_by":[{"field":"album__year","direction":"desc"}]}
http://localhost:/album?q={"order_by":[{"field":"artist__genre","direction":"desc"}]}
http://localhost:/song?q={"order_by":[{"field":"artist__name","direction":"desc"}]}
http://localhost:/song?q={"order_by":[{"field":"name","direction":"desc"}]}

Artists:

http://localhost:/artist?q={"order_by":[{"field":"name","direction":"desc"}]}
http://localhost:/artist?q={"order_by":[{"field":"name","direction":"desc"}]}
http://localhost:/artist?q={"order_by":[{"field":"genre","direction":"desc"}]}
http://localhost:/artist?q={"order_by":[{"field":"concerts__time","direction":"desc"}]}

Cities: 

http://localhost:/city?q={"order_by":[{"field":"name","direction":"desc"}]}
http://localhost:/city?q={"order_by":[{"field":"state","direction":"desc"}]}
http://localhost:/city?q={"order_by":[{"field":"time","direction":"desc"}]}

**Comment by ChiaHuaLu** [comment]
Probably spent like 3 hours to do front end drop down
