### ISSUE TITLE
[4] I want to see at least 3 pages for City Model

### ISSUE THREAD

**Issue by ccmmaa** [ccmmaa/idb#8]
-data
-external links
-embedded images (e.g. Bing, Flickr, Google)
-embedded videos (e.g. Bing, Google, Vimeo)
-embedded maps (e.g. Google Maps)
-embedded social network feeds (e.g. Facebook, Twitter)
-links to Artists
-links to Songs

**Comment by SabrinaHerrero** [comment]
For the example, use Austin, Houston, and New York

**Comment by SabrinaHerrero** [comment]
Austin

popular genres in this city
concerts
links to artists
city playlist
links to songs from playlist

**Comment by SabrinaHerrero** [comment]
Had so much trouble working with the bootstrap. Ended up deleting parts of the template and writing my own html/css

**Comment by SabrinaHerrero** [comment]
Might want to add extra information in the future
