### ISSUE TITLE
(Est 4 hrs) Implement searching for model pages [Act ]

### ISSUE THREAD

**Issue by ccmmaa** [ccmmaa/idb#84]

**Comment by ccmmaa** [comment]
1 hr. looked at some algorithms for searching. found https://www.red-gate.com/simple-talk/sql/t-sql-programming/searching-for-strings-in-sql-server-databases/

**Comment by ccmmaa** [comment]
/artist?q={"filters":[{"name":"name","op":"like","val":"%<>%"}]}
/artist?q={"filters":[{"name":"bio","op":"like","val":"%<>%"}]}
/artist?q={"filters":[{"name":"genre","op":"like","val":"%<>%"}]}

/album?q={"filters":[{"name":"name","op":"like","val":"%<>%"}]}
/album?q={"filters":[{"name":"year","op":"like","val":"%<>%"}]}
/album?q={"filters":[{"name":"producer","op":"like","val":"%<>%"}]}

/city?q={"filters":[{"name":"name","op":"like","val":"%<>%"}]}
/city?q={"filters":[{"name":"state","op":"like","val":"%<>%"}]}
/city?q={"filters":[{"name":"concerts__time","op":"like","val":"%<>%"}]}
/city?q={"filters":[{"name":"concerts__venue","op":"like","val":"%<>%"}]}

/song?q={"filters":[{"name":"name","op":"like","val":"%<>%"}]}
/song?q={"filters":[{"name":"lyrics","op":"like","val":"%<>%"}]}

**Comment by ccmmaa** [comment]
This Javascript code is for the search page to show the instances of the search entry that were found in a large string along with some of the words before and after it. Like how Google shows the instances of your search input along with the words around it.

//returns a string of instances that contain the searchInput. The instances will be padded by numWordsBefAndAft words and will be followed by a "..."
//searchInput is the string that the user searched for
//strToSearchThrough is the string that at least one instance of searchInput was found in
//numWordsBefAndAft is the int of the number of words you want to appear before and after the instances that are found in strToSearchThrough
//numOfSearchInputToFind is the int of the num of instances of searchInput you want to find in strToSearchThrough
function getHighlightedEntries (searchInput, strToSearchThrough, numWordsBefAndAft, numOfSearchInputToFind) {
        
        var continueSearch = true;
        var lastIndex = 0;
        var searchInputIndexes = [];
        var curIndex = 0;
        
        //go through and find the indexes of the first numOfSearchInputToFind instances of searchInput
        for(i = 0; continueSearch && i < numOfSearchInputToFind; i++){
                curIndex = strToSearchThrough.indexOf(searchInput, lastIndex);
                if(curIndex == -1){
                        //if we reached the end, stop searching
                        continueSearch = false;
                } else {
                        //otherwise add the index to the array and 
                        searchInputIndexes[i] = curIndex;
                        lastIndex = curIndex + 1;
                }
        }
        
        var returnString = "";
        var spaceIndexes = [];
        var spaceIndexCount = 0;
        var curInput = 0;
        var curStart = 0;
        var curEnd = 0;
        
        for(i = 0; i < searchInputIndexes.length; i++){
                var numWordsAfterCount = 0;
                var goToNextInputIndex = false;
                lastIndex = searchInputIndexes[i];
                while(!goToNextInputIndex){
                        curIndex = strToSearchThrough.indexOf(" ", lastIndex);
                        
                        //if we reached the end, add the last padded instance and goToNextInputIndex(i.e. break out)
                        if(curIndex == -1){
                                var substr = strToSearchThrough.substring(spaceIndexes[curStart]);
                                returnString = returnString.concat(substr + "...");
                                goToNextInputIndex = true;
                        }
                        
                        //set lastIndex for the next call to indexOf and add curIndex to the array
                        lastIndex = curIndex + 1;
                        spaceIndexes[spaceIndexCount] = curIndex;
                        spaceIndexCount++;
                        
                        if(curIndex < searchInputIndexes[i]){
                                //if the index is less than i then it can be the start of the current padded instance
                                if(spaceIndexes.length - 2 - curStart == numWordsBefAndAft){
                                        curStart = spaceIndexes.length - numWordsBefAndAft;
                                }
                        }
                        if(curIndex > (searchInputIndexes[i] + searchInput.length)){
                                //if the index is greater than the index and the searchInput length then it can be the start of the current padded instance
                                numWordsAfterCount++;
                                curEnd = spaceIndexes.length - 1;
                                if(numWordsAfterCount == numWordsBefAndAft){
                                        //Found the entire padded instance, concatenate it to the string we are returning and goToNextIndex
                                        var substr = strToSearchThrough.substring(spaceIndexes[curStart], spaceIndexes[curEnd]);
                                        returnString = returnString.concat(substr + "...");
                                        goToNextInputIndex = true;
                                }
                        }
                }
        }
        return returnString
}

**Comment by Laurencez** [comment]
can search through multiple attribute fields using or:

/album?q={"filters":[{"or":[{"name":"name","op":"like","val":"%<>%"}, {"name":"year","op":"like","val":"%<>%"}, {"name":"name","op":"like","val":"%<>%"}]}]}

**Comment by Laurencez** [comment]
Search function now works on website. All different models have their own pagination on the search result page. Still need to implement highlighting and make edits to the information displayed.

**Comment by Laurencez** [comment]
Added highlighting function and bios/lyrics to search results in scroll bar. Total time so far estimated 13hrs.
