### ISSUE TITLE
Remove duplicates from database

### ISSUE THREAD

**Issue by ccmmaa** [ccmmaa/idb#99]

**Comment by ccmmaa** [comment]
removed dup artists

**Comment by SabrinaHerrero** [comment]
82 duplicate albums

**Comment by SabrinaHerrero** [comment]
all duplicate albums removed

**Comment by SabrinaHerrero** [comment]
will be leaving duplicate songs as they are part of different albums

**Comment by SabrinaHerrero** [comment]
This was helpful in finding duplicates https://stackoverflow.com/questions/2594829/finding-duplicate-values-in-a-sql-table

**Comment by SabrinaHerrero** [comment]
All duplicates are removed
